[_shk_prx_elf_substitute]
# ASM function ported to PRX to make room for the loader
# Don't remove this
addr = 0x5F7140
emit_trampoline = false

[game_loop_intro_start]
addr = 0x11020
replaced_instr = "stdu r1, -0xc0(r1)"

[game_loop_start]
addr = 0x502d80
replaced_instr = "stdu r1, -0x70(r1)"

[STUB_0006544c]
addr = 0x4f69b8
replaced_instr = "stdu r1, -0x240(r1)"

[authenticate_game]
addr = 0x5046b0
replaced_instr = "stdu r1, -0x90(r1)"

[on_respawn]
addr = 0x7f018
replaced_instr = "stdu r1, -0xb0(r1)"

[wrench_update_func]
addr = 0x42c150
replaced_instr = "stdu r1, -0x2a0(r1)"

[FUN_000784e8]
addr = 0x68560
replaced_instr = "stdu r1, -0x70(r1)"

[bink_do_frame]
addr = 0x5f0370
replaced_instr = "stdu r1, -0x41e0(r1)"

[perform_save_action]
addr = 0x4e7a34
replaced_instr = "stdu r1, -0xa0(r1)"

[cellGameBootCheck]
addr = 0x4f66c4
replaced_instr = "stdu r1, -0x1b0(r1)"

[cellGameContentPermit]
addr = 0x4f64bc
replaced_instr = "stdu r1, -0x120(r1)"

[goldBoltUpdate]
addr = 0x1d9d48
replaced_instr = "stdu r1, -0x140(r1)"

[_start_in_level_movie]
addr = 0x167e60
replaced_instr = "stdu r1, -0x1a0(r1)"

[_unlock_item]
addr = 0x112e18
replaced_instr = "stdu r1, -0xb0(r1)"

[_unlock_level]
addr = 0x112c20
replaced_instr = "stdu r1, -0xe0(r1)"

[_unlock_skillpoint]
addr = 0x11b728
replaced_instr = "stdu r1, -0xa0(r1)"

[metal_detector_spot_update_func]
addr = 0x3d91b8
replaced_instr = "stdu r1, -0xa0(r1)"

[menu_item_tick]
addr = 0x141408
replaced_instr = "stdu r1, -0xc0(r1)"

[set_ratchet_animation]
addr = 0x85300
replaced_instr = "stdu r1, -0xc0(r1)"

[_spawn_moby]
addr = 0xefa28
replaced_instr = "stdu r1, -0x80(r1)"

[_moby_get_damage]
addr = 0x10675c
replaced_instr = "cmpwi cr1, r5, 0x0"
