0x650CB4 = 0x9f18429d  # replace _sys_process_at_Exitspawn with sys_prx_start_module

# redirect call to cellGameBootCheck
0x4eef4c = [
    "bla 0x4f66c4",
    "nop"
]

# redirect call to cellGameContentPermit
0x4eefe0 = 0x428074dd
0x4eefe4 = "nop"

0x013044 = 0x48000110
0x0131C8 = 0x4800017C
0x013358 = 0x4800005C
0x013424 = 0x48000114
0x13da40 = "nop"
0x012480 = 0x428001fc

# Don't play cutscenes after purchasing weapons from vendor
0x16dd90 = "li r30, 0"

# Don't force unlock current level when going to levels
0x4d3170 = "nop"

# Don't force current weapon to Bomb Glove if we don't have it
0x4d2f6c = "nop"

# Remove calls to display_prompt for save/load menu options
0x141810 = "nop"
0x141870 = "nop"

# Sample for non in-place patching. Forces Visibomb for any item bought in the vendor.
#[0x16d864]
#in_place = false
#instructions = [
#    "li r3, 0x0d",
##    "extsw r3,r3"  # Optionally add the instruction you replaced
#]

# helga patch
0x4a2eb0 = "lis r3, 0xb0"
0x4a2eb4 = "addic r3, r3, 0x2"

# aww heck guy patch
## unlock item
0x32d0d8 = "nop"
0x32d0fc = "li r3, 49"
0x32d100 = "bl 0x112e18"
0x32d050 = "lis r3, 0xb0"
## delete check
0x32d054 = "addic r3, r3, 0x2"
0x32d058 = "lbz r3, 0x31(r3)"

# infobot patch
0x44bd58 = "lis r4, 0xb0"
0x44bd5c = "addic r4, r4, 0x100"
0x44b9d0 = "lis r3, 0xb0"
0x44b9d8 = "addic r3, r3, 0x100"
0x44b940 = "lis r4, 0xb0"
0x44b944 = "addic r4, r4, 0x100"

# plumber
0x4558b0 = "lis r3, 0xb0"
0x4558b4 = "addic r3, r3, 0x100"

# skid
0x45d220 = "lis r3, 0xb0"
0x45d224 = "addic r3, r3, 0x1e"

# gold weapon vendor patch
## 0x339d64: ??? # lis r5, 0xB0
## 0x339d74: ??? # addic r5, 0x37
## 0x339c10: ??? # lis r5, 0xB0
## 0x339c20: ??? # addic r5, 0x37
## missing call to unlock_item